name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: apt list --all-versions docker*
      - run: apt list --installed docker*
